- name: "Remove and cleanup"
  hosts: 
    - "all"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  ignore_errors: true
  vars_files:
    - "config.yaml"
  tasks:
      - name: "Stop the apache webserver"
        ansible.builtin.service:
          name: "httpd"
          state: "stopped"
          enabled: false

      - name: "Remove the apache web server"
        ansible.builtin.package:
          name: "httpd"
          state: "absent"

      - name: "Close firewall"
        ansible.posix.firewalld:
          port: "{{ config[inventory_hostname].port }}/tcp"
          state: "disabled"
          immediate: true
          permanent: true
        when: "config[inventory_hostname].port is defined"

      - name: "Close firewall"
        ansible.posix.firewalld:
          port: "{{ config['default'].port }}/tcp"
          state: "disabled"
          immediate: true
          permanent: true
        when: "config[inventory_hostname].port is not defined"

      - name: "Remove content"
        ansible.builtin.file:
          state: "absent"
          path: "/var/www/html"
      - fail:
        ignore_errors: false
