- name: "Remove and cleanup"
  hosts:
    - "web1"
    - "web2"
    - "web3"
    - "web4"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  ignore_errors: true
  vars_files:
    - "config.yaml"
  tasks:
    - name: "Stop the apache webserver"
      service:
        name: "httpd"
        state: "stopped"
        enabled: false

    - name: "Remove the apache web server"
      ansible.builtin.package:
        name: "httpd"
        state: "absent"

    - name: "Close firewall"
      ansible.posix.firewalld:
        port: "{{ config[inventory_hostname].port }}/tcp"
        state: "disabled"
        immediate: true
        permanent: true

      when: "config[inventory_hostname].port is defined"

    - name: "Close firewall"
      ansible.posix.firewalld:
        port: "80/tcp"
        state: "disabled"
        immediate: true
        permanent: true
      when: "config[inventory_hostname].port is not defined"

    - name: "Remove content"
      file:
        state: "absent"
        path: "/var/www/html"

