- name: "Add installed hosts"
  hosts: "localhost"
  gather_facts: false
  tasks:
    - include_tasks: "add_hosts.yaml"
      vars:
        group_name: "hosts_to_configure"
        host_list: "{{ successfull_hosts }}"

- name: "Configure the apache webserver"
  hosts: 
    - "all"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  vars_files:
    - "config.yaml"
  tasks:
    - block:
      - name: "Deploy configuration file"
        ansible.builtin.template:
          src: "httpd.conf.j2"
          dest: "/etc/httpd/conf/httpd.conf"

      - name: "Put webserver content in place"
        ansible.builtin.copy:
          src: "content/{{ inventory_hostname }}/"
          dest: "/var/www/html/"

      - name: "Start the service"
        ansible.builtin.service:
          name: "httpd"
          enabled: true
          state: "started"
      always:
        - include_tasks: "get_result.yaml"
          vars:
            stage: "configuration"
