config:
  default:
    port: 80
    servername: "{{ ansible_fqdn }}:80"
  web1: 
    port: 80
    servername: web1.example.com
  web2:
    port: 80
    servername: web2.example.com
  webtest:
    port: 8080
    servername: webtest.example.com

