- name: "Configure the apache webserver"
  hosts: "all"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  vars_files:
    - "config.yaml"
  tasks:
    - name: "Deploy configuration file"
      ansible.builtin.template:
        src: "httpd.conf.j2"
        dest: "/etc/httpd/conf/httpd.conf"
    - debug:
        var: ansible_play_hosts
    - debug:
        var: ansible_play_hosts_all
    - fail:

    - name: "Put webserver content in place"
      ansible.builtin.copy:
        src: "content/{{ inventory_hostname }}/"
        dest: "/var/www/html/"


    - name: "Start the service"
      ansible.builtin.service:
        name: "httpd"
        enabled: true
        state: "started"

    - name: "Set success state"
      ansible.builtin.file:
        path: "/var/run/web_install_success"
        state: "touch"

  handlers:
    - name: "restart_httpd"
      ansible.builtin.service:
        name: "httpd"
        state: "restarted"
