- name: "Install the apache webserver"
  hosts: 
    - "all"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  vars_files:
    - "config.yaml"
  tasks:
      - name: "Make sure appache is installed"
        ansible.builtin.package:
          name: "httpd"
          state: "latest"
