- name: "Install teh apache webserver"
  hosts: "all"
  user: "devops"
  become: true
  become_user: "root"
  become_method: "sudo"
  vars_files:
    - "config.yaml"
  tasks:
    - set_fact:
       ansible_play_hosts:
         - web2

    - debug:
        var: ansible_play_hosts

    - name: "Make sure appache is installed"
      ansible.builtin.package:
        name: "httpd"
        state: "latest"

    - name: "Open firewall"
      ansible.posix.firewalld:
        port: "{{ config[inventory_hostname].port }}/tcp"
        state: "enabled"
      when: "config[inventory_hostname].port is defined"

    - name: "Open firewall"
      ansible.posix.firewalld:
        port: "80/tcp"
        state: "enabled"
      when: "config[inventory_hostname].port is not defined"

    - set_stats:
        data:
           failed_hosts:
                   - web2
